services:
  todo-server:
    image: 95.216.219.12:5000/todo-server
    ports:
    - 8081:8081
  integration-test:
    image: 95.216.219.12:5000/todo-cli
    depends_on:
      - todo-server
    command: ./integration-test.sh
  functional-test:
    image: 95.216.219.12:5000/todo-server
    command: bash -c "./todo-server && ./functional-test.sh"
